server:
  port: 80
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
     probability: 1


eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用ip地址
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/
      defaultZone: http://eureka7001.com:7001/eureka/