server:
  port: 7003


eureka:
  instance:
    hostname: eureka7003.com #eureka主机名
  client:
    register-with-eureka: false #是否将eureka注册进注册机里面
    fetch-registry: false #不从eureka中获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
